//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.26 at 10:23:17 AM MST 
//


package com.outjected.smartystreets.response;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="candidate" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="input_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="candidate_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="addressee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="delivery_line_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="delivery_line_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="last_line" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="delivery_point_barcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="components">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="urbanization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="primary_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="street_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="street_predirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="street_postdirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="street_suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="secondary_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="secondary_designator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="pmb_designator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="pmb_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="city_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="state_abbreviation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="plus4_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="delivery_point" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="delivery_point_check_digit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="metadata">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="record_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="county_fips" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="county_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="carrier_route" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="congressional_district" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="building_default_indicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="rdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="precision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="analysis">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="dpv_match_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="dpv_footnotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="dpv_cmra" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="dpv_vacant" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ews_match" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="footnotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="lacslink_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="lasclink_indicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "candidate"
})
@XmlRootElement(name = "candidates")
public class Candidates {

    @XmlElement(required = true)
    protected List<Candidates.Candidate> candidate;

    /**
     * Gets the value of the candidate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the candidate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCandidate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Candidates.Candidate }
     * 
     * 
     */
    public List<Candidates.Candidate> getCandidate() {
        if (candidate == null) {
            candidate = new ArrayList<Candidates.Candidate>();
        }
        return this.candidate;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="input_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *         &lt;element name="candidate_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *         &lt;element name="addressee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="delivery_line_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="delivery_line_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="last_line" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="delivery_point_barcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="components">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="urbanization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="primary_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="street_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="street_predirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="street_postdirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="street_suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="secondary_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="secondary_designator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="pmb_designator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="pmb_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="city_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="state_abbreviation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="plus4_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="delivery_point" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="delivery_point_check_digit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="metadata">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="record_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="county_fips" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="county_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="carrier_route" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="congressional_district" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="building_default_indicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="rdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="precision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="analysis">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="dpv_match_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="dpv_footnotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="dpv_cmra" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="dpv_vacant" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ews_match" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="footnotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="lacslink_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="lasclink_indicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "inputIndex",
        "candidateIndex",
        "addressee",
        "deliveryLine1",
        "deliveryLine2",
        "lastLine",
        "deliveryPointBarcode",
        "components",
        "metadata",
        "analysis"
    })
    public static class Candidate {

        @XmlElement(name = "input_index")
        @XmlSchemaType(name = "unsignedInt")
        protected long inputIndex;
        @XmlElement(name = "candidate_index")
        @XmlSchemaType(name = "unsignedInt")
        protected long candidateIndex;
        protected String addressee;
        @XmlElement(name = "delivery_line_1")
        protected String deliveryLine1;
        @XmlElement(name = "delivery_line_2")
        protected String deliveryLine2;
        @XmlElement(name = "last_line")
        protected String lastLine;
        @XmlElement(name = "delivery_point_barcode")
        protected String deliveryPointBarcode;
        @XmlElement(required = true)
        protected Candidates.Candidate.Components components;
        @XmlElement(required = true)
        protected Candidates.Candidate.Metadata metadata;
        @XmlElement(required = true)
        protected Candidates.Candidate.Analysis analysis;

        /**
         * Gets the value of the inputIndex property.
         * 
         */
        public long getInputIndex() {
            return inputIndex;
        }

        /**
         * Sets the value of the inputIndex property.
         * 
         */
        public void setInputIndex(long value) {
            this.inputIndex = value;
        }

        /**
         * Gets the value of the candidateIndex property.
         * 
         */
        public long getCandidateIndex() {
            return candidateIndex;
        }

        /**
         * Sets the value of the candidateIndex property.
         * 
         */
        public void setCandidateIndex(long value) {
            this.candidateIndex = value;
        }

        /**
         * Gets the value of the addressee property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressee() {
            return addressee;
        }

        /**
         * Sets the value of the addressee property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressee(String value) {
            this.addressee = value;
        }

        /**
         * Gets the value of the deliveryLine1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeliveryLine1() {
            return deliveryLine1;
        }

        /**
         * Sets the value of the deliveryLine1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeliveryLine1(String value) {
            this.deliveryLine1 = value;
        }

        /**
         * Gets the value of the deliveryLine2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeliveryLine2() {
            return deliveryLine2;
        }

        /**
         * Sets the value of the deliveryLine2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeliveryLine2(String value) {
            this.deliveryLine2 = value;
        }

        /**
         * Gets the value of the lastLine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastLine() {
            return lastLine;
        }

        /**
         * Sets the value of the lastLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastLine(String value) {
            this.lastLine = value;
        }

        /**
         * Gets the value of the deliveryPointBarcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeliveryPointBarcode() {
            return deliveryPointBarcode;
        }

        /**
         * Sets the value of the deliveryPointBarcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeliveryPointBarcode(String value) {
            this.deliveryPointBarcode = value;
        }

        /**
         * Gets the value of the components property.
         * 
         * @return
         *     possible object is
         *     {@link Candidates.Candidate.Components }
         *     
         */
        public Candidates.Candidate.Components getComponents() {
            return components;
        }

        /**
         * Sets the value of the components property.
         * 
         * @param value
         *     allowed object is
         *     {@link Candidates.Candidate.Components }
         *     
         */
        public void setComponents(Candidates.Candidate.Components value) {
            this.components = value;
        }

        /**
         * Gets the value of the metadata property.
         * 
         * @return
         *     possible object is
         *     {@link Candidates.Candidate.Metadata }
         *     
         */
        public Candidates.Candidate.Metadata getMetadata() {
            return metadata;
        }

        /**
         * Sets the value of the metadata property.
         * 
         * @param value
         *     allowed object is
         *     {@link Candidates.Candidate.Metadata }
         *     
         */
        public void setMetadata(Candidates.Candidate.Metadata value) {
            this.metadata = value;
        }

        /**
         * Gets the value of the analysis property.
         * 
         * @return
         *     possible object is
         *     {@link Candidates.Candidate.Analysis }
         *     
         */
        public Candidates.Candidate.Analysis getAnalysis() {
            return analysis;
        }

        /**
         * Sets the value of the analysis property.
         * 
         * @param value
         *     allowed object is
         *     {@link Candidates.Candidate.Analysis }
         *     
         */
        public void setAnalysis(Candidates.Candidate.Analysis value) {
            this.analysis = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="dpv_match_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="dpv_footnotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="dpv_cmra" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="dpv_vacant" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ews_match" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="footnotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="lacslink_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="lasclink_indicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dpvMatchCode",
            "dpvFootnotes",
            "dpvCmra",
            "dpvVacant",
            "active",
            "ewsMatch",
            "footnotes",
            "lacslinkCode",
            "lasclinkIndicator"
        })
        public static class Analysis {

            @XmlElement(name = "dpv_match_code")
            protected String dpvMatchCode;
            @XmlElement(name = "dpv_footnotes")
            protected String dpvFootnotes;
            @XmlElement(name = "dpv_cmra")
            protected String dpvCmra;
            @XmlElement(name = "dpv_vacant")
            protected String dpvVacant;
            protected String active;
            @XmlElement(name = "ews_match")
            protected String ewsMatch;
            protected String footnotes;
            @XmlElement(name = "lacslink_code")
            protected String lacslinkCode;
            @XmlElement(name = "lasclink_indicator")
            protected String lasclinkIndicator;

            /**
             * Gets the value of the dpvMatchCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDpvMatchCode() {
                return dpvMatchCode;
            }

            /**
             * Sets the value of the dpvMatchCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDpvMatchCode(String value) {
                this.dpvMatchCode = value;
            }

            /**
             * Gets the value of the dpvFootnotes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDpvFootnotes() {
                return dpvFootnotes;
            }

            /**
             * Sets the value of the dpvFootnotes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDpvFootnotes(String value) {
                this.dpvFootnotes = value;
            }

            /**
             * Gets the value of the dpvCmra property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDpvCmra() {
                return dpvCmra;
            }

            /**
             * Sets the value of the dpvCmra property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDpvCmra(String value) {
                this.dpvCmra = value;
            }

            /**
             * Gets the value of the dpvVacant property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDpvVacant() {
                return dpvVacant;
            }

            /**
             * Sets the value of the dpvVacant property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDpvVacant(String value) {
                this.dpvVacant = value;
            }

            /**
             * Gets the value of the active property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActive() {
                return active;
            }

            /**
             * Sets the value of the active property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActive(String value) {
                this.active = value;
            }

            /**
             * Gets the value of the ewsMatch property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEwsMatch() {
                return ewsMatch;
            }

            /**
             * Sets the value of the ewsMatch property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEwsMatch(String value) {
                this.ewsMatch = value;
            }

            /**
             * Gets the value of the footnotes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFootnotes() {
                return footnotes;
            }

            /**
             * Sets the value of the footnotes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFootnotes(String value) {
                this.footnotes = value;
            }

            /**
             * Gets the value of the lacslinkCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLacslinkCode() {
                return lacslinkCode;
            }

            /**
             * Sets the value of the lacslinkCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLacslinkCode(String value) {
                this.lacslinkCode = value;
            }

            /**
             * Gets the value of the lasclinkIndicator property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLasclinkIndicator() {
                return lasclinkIndicator;
            }

            /**
             * Sets the value of the lasclinkIndicator property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLasclinkIndicator(String value) {
                this.lasclinkIndicator = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="urbanization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="primary_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="street_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="street_predirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="street_postdirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="street_suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="secondary_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="secondary_designator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="pmb_designator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="pmb_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="city_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="state_abbreviation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="plus4_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="delivery_point" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="delivery_point_check_digit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "urbanization",
            "primaryNumber",
            "streetName",
            "streetPredirection",
            "streetPostdirection",
            "streetSuffix",
            "secondaryNumber",
            "secondaryDesignator",
            "pmbDesignator",
            "pmbNumber",
            "cityName",
            "stateAbbreviation",
            "zipcode",
            "plus4Code",
            "deliveryPoint",
            "deliveryPointCheckDigit"
        })
        public static class Components {

            protected String urbanization;
            @XmlElement(name = "primary_number")
            protected String primaryNumber;
            @XmlElement(name = "street_name")
            protected String streetName;
            @XmlElement(name = "street_predirection")
            protected String streetPredirection;
            @XmlElement(name = "street_postdirection")
            protected String streetPostdirection;
            @XmlElement(name = "street_suffix")
            protected String streetSuffix;
            @XmlElement(name = "secondary_number")
            protected String secondaryNumber;
            @XmlElement(name = "secondary_designator")
            protected String secondaryDesignator;
            @XmlElement(name = "pmb_designator")
            protected String pmbDesignator;
            @XmlElement(name = "pmb_number")
            protected String pmbNumber;
            @XmlElement(name = "city_name")
            protected String cityName;
            @XmlElement(name = "state_abbreviation")
            protected String stateAbbreviation;
            protected String zipcode;
            @XmlElement(name = "plus4_code")
            protected String plus4Code;
            @XmlElement(name = "delivery_point")
            protected String deliveryPoint;
            @XmlElement(name = "delivery_point_check_digit")
            protected String deliveryPointCheckDigit;

            /**
             * Gets the value of the urbanization property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrbanization() {
                return urbanization;
            }

            /**
             * Sets the value of the urbanization property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrbanization(String value) {
                this.urbanization = value;
            }

            /**
             * Gets the value of the primaryNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrimaryNumber() {
                return primaryNumber;
            }

            /**
             * Sets the value of the primaryNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrimaryNumber(String value) {
                this.primaryNumber = value;
            }

            /**
             * Gets the value of the streetName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStreetName() {
                return streetName;
            }

            /**
             * Sets the value of the streetName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStreetName(String value) {
                this.streetName = value;
            }

            /**
             * Gets the value of the streetPredirection property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStreetPredirection() {
                return streetPredirection;
            }

            /**
             * Sets the value of the streetPredirection property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStreetPredirection(String value) {
                this.streetPredirection = value;
            }

            /**
             * Gets the value of the streetPostdirection property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStreetPostdirection() {
                return streetPostdirection;
            }

            /**
             * Sets the value of the streetPostdirection property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStreetPostdirection(String value) {
                this.streetPostdirection = value;
            }

            /**
             * Gets the value of the streetSuffix property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStreetSuffix() {
                return streetSuffix;
            }

            /**
             * Sets the value of the streetSuffix property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStreetSuffix(String value) {
                this.streetSuffix = value;
            }

            /**
             * Gets the value of the secondaryNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSecondaryNumber() {
                return secondaryNumber;
            }

            /**
             * Sets the value of the secondaryNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSecondaryNumber(String value) {
                this.secondaryNumber = value;
            }

            /**
             * Gets the value of the secondaryDesignator property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSecondaryDesignator() {
                return secondaryDesignator;
            }

            /**
             * Sets the value of the secondaryDesignator property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSecondaryDesignator(String value) {
                this.secondaryDesignator = value;
            }

            /**
             * Gets the value of the pmbDesignator property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPmbDesignator() {
                return pmbDesignator;
            }

            /**
             * Sets the value of the pmbDesignator property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPmbDesignator(String value) {
                this.pmbDesignator = value;
            }

            /**
             * Gets the value of the pmbNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPmbNumber() {
                return pmbNumber;
            }

            /**
             * Sets the value of the pmbNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPmbNumber(String value) {
                this.pmbNumber = value;
            }

            /**
             * Gets the value of the cityName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCityName() {
                return cityName;
            }

            /**
             * Sets the value of the cityName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCityName(String value) {
                this.cityName = value;
            }

            /**
             * Gets the value of the stateAbbreviation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStateAbbreviation() {
                return stateAbbreviation;
            }

            /**
             * Sets the value of the stateAbbreviation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStateAbbreviation(String value) {
                this.stateAbbreviation = value;
            }

            /**
             * Gets the value of the zipcode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZipcode() {
                return zipcode;
            }

            /**
             * Sets the value of the zipcode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZipcode(String value) {
                this.zipcode = value;
            }

            /**
             * Gets the value of the plus4Code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPlus4Code() {
                return plus4Code;
            }

            /**
             * Sets the value of the plus4Code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPlus4Code(String value) {
                this.plus4Code = value;
            }

            /**
             * Gets the value of the deliveryPoint property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDeliveryPoint() {
                return deliveryPoint;
            }

            /**
             * Sets the value of the deliveryPoint property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDeliveryPoint(String value) {
                this.deliveryPoint = value;
            }

            /**
             * Gets the value of the deliveryPointCheckDigit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDeliveryPointCheckDigit() {
                return deliveryPointCheckDigit;
            }

            /**
             * Sets the value of the deliveryPointCheckDigit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDeliveryPointCheckDigit(String value) {
                this.deliveryPointCheckDigit = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="record_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="county_fips" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="county_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="carrier_route" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="congressional_district" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="building_default_indicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="rdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="precision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "recordType",
            "countyFips",
            "countyName",
            "carrierRoute",
            "congressionalDistrict",
            "buildingDefaultIndicator",
            "rdi",
            "latitude",
            "longitude",
            "precision"
        })
        public static class Metadata {

            @XmlElement(name = "record_type")
            protected String recordType;
            @XmlElement(name = "county_fips")
            protected String countyFips;
            @XmlElement(name = "county_name")
            protected String countyName;
            @XmlElement(name = "carrier_route")
            protected String carrierRoute;
            @XmlElement(name = "congressional_district")
            protected String congressionalDistrict;
            @XmlElement(name = "building_default_indicator")
            protected String buildingDefaultIndicator;
            protected String rdi;
            protected BigDecimal latitude;
            protected BigDecimal longitude;
            protected String precision;

            /**
             * Gets the value of the recordType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordType() {
                return recordType;
            }

            /**
             * Sets the value of the recordType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordType(String value) {
                this.recordType = value;
            }

            /**
             * Gets the value of the countyFips property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountyFips() {
                return countyFips;
            }

            /**
             * Sets the value of the countyFips property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountyFips(String value) {
                this.countyFips = value;
            }

            /**
             * Gets the value of the countyName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountyName() {
                return countyName;
            }

            /**
             * Sets the value of the countyName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountyName(String value) {
                this.countyName = value;
            }

            /**
             * Gets the value of the carrierRoute property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCarrierRoute() {
                return carrierRoute;
            }

            /**
             * Sets the value of the carrierRoute property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCarrierRoute(String value) {
                this.carrierRoute = value;
            }

            /**
             * Gets the value of the congressionalDistrict property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCongressionalDistrict() {
                return congressionalDistrict;
            }

            /**
             * Sets the value of the congressionalDistrict property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCongressionalDistrict(String value) {
                this.congressionalDistrict = value;
            }

            /**
             * Gets the value of the buildingDefaultIndicator property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBuildingDefaultIndicator() {
                return buildingDefaultIndicator;
            }

            /**
             * Sets the value of the buildingDefaultIndicator property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBuildingDefaultIndicator(String value) {
                this.buildingDefaultIndicator = value;
            }

            /**
             * Gets the value of the rdi property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRdi() {
                return rdi;
            }

            /**
             * Sets the value of the rdi property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRdi(String value) {
                this.rdi = value;
            }

            /**
             * Gets the value of the latitude property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setLatitude(BigDecimal value) {
                this.latitude = value;
            }

            /**
             * Gets the value of the longitude property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getLongitude() {
                return longitude;
            }

            /**
             * Sets the value of the longitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setLongitude(BigDecimal value) {
                this.longitude = value;
            }

            /**
             * Gets the value of the precision property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrecision() {
                return precision;
            }

            /**
             * Sets the value of the precision property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrecision(String value) {
                this.precision = value;
            }

        }

    }

}
