//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.26 at 10:23:17 AM MST 
//


package com.outjected.smartystreets.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.outjected.smartystreets.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.outjected.smartystreets.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Candidates }
     * 
     */
    public Candidates createCandidates() {
        return new Candidates();
    }

    /**
     * Create an instance of {@link Candidates.Candidate }
     * 
     */
    public Candidates.Candidate createCandidatesCandidate() {
        return new Candidates.Candidate();
    }

    /**
     * Create an instance of {@link Candidates.Candidate.Components }
     * 
     */
    public Candidates.Candidate.Components createCandidatesCandidateComponents() {
        return new Candidates.Candidate.Components();
    }

    /**
     * Create an instance of {@link Candidates.Candidate.Metadata }
     * 
     */
    public Candidates.Candidate.Metadata createCandidatesCandidateMetadata() {
        return new Candidates.Candidate.Metadata();
    }

    /**
     * Create an instance of {@link Candidates.Candidate.Analysis }
     * 
     */
    public Candidates.Candidate.Analysis createCandidatesCandidateAnalysis() {
        return new Candidates.Candidate.Analysis();
    }

}
